import bcrypt from 'bcryptjs';

const data = {
  config: {
    cambioManual: 2000,
    tasaIva: 12,
    otrosImp: 2,
    montoEnvio: 9,
    mostrarBs: false,
    mostrarBcv: false,
  },
  users: [
    {
      name: 'Franklin',
      email: 'frank.uah@gmail.com',
      password: bcrypt.hashSync('1331', 8),
      isAdmin: true,
    },
    {
      name: 'Alejandro',
      email: 'alejandro@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    }
  ],


  productos: [
    {
      nombre: "Camisa manga corta azul",
      imagen: "/images/p1.jpg",
      marca: "Adidas",
      categoria: "camisas",
      descripcion: "Comoda camisa manga corta con bellos estampados",
      precio: 120,
      countInStock: 7,
      rating: 4.5,
      numReviews: 10,
    },
    {
      nombre: "Torta Huevos de Pascua",
      imagen: "/images/p2.jpg",
      marca: "Divinas Tentaciones",
      categoria: "tortas",
      descripcion: "Deliciosa torta de chocolate y vainilla",
      precio: 60,
      countInStock: 4,
      rating: 3,
      numReviews: 5,
    },
    {
      nombre: "Litografia de Coca-Cola",
      imagen: "/images/p3.jpg",
      marca: "coca-cola",
      categoria: "afiches",
      descripcion: "Litografia Conmemorativa Aniversario de Coca-Cola",
      precio: 10.50,
      countInStock: 12,
      rating: 3,
      numReviews: 15,
    },
    {
      nombre: "Torta Cumpleaños Personalizado",
      imagen: "/images/p4.jpg",
      marca: "divinas tentaciones",
      categoria: "tortas",
      descripcion: "Deliciosa torta de cumpleaños con figuras solicitadas",
      precio: 25,
      countInStock: 15,
      rating: 3,
      numReviews: 25,
    },
    {
      nombre: "Dulce Variados",
      imagen: "/images/p5.jpg",
      marca: "divinas tentaciones",
      categoria: "dulces",
      descripcion: "Deliciosos dulces variados",
      precio: 15.75,
      countInStock: 12,
      rating: 4.5,
      numReviews: 80,
    },
    {
      nombre: "Reloj Fitbit Inteligente",
      imagen: "/images/p6.jpg",
      marca: "Takoi",
      categoria: "relojes",
      descripcion: "Practico reloj monitor de ejericios",
      precio: 32.75,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
    {
      nombre: "Torta Carmin",
      imagen: "/images/p7.jpg",
      marca: "divinas tentaciones",
      categoria: "tortas",
      descripcion: "Deliciosa torta de fresa y vainilla",
      precio: 32.75,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
    {
      nombre: "Pantalon Crudo",
      imagen: "/images/p8.jpg",
      marca: "dockers",
      categoria: "pantalones",
      descripcion: "Comodo pantalon color verde oliva",
      precio: 30.00,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
    {
      nombre: "Pantalon de Lino",
      imagen: "/images/p9.jpg",
      marca: "dockers",
      categoria: "pantalones",
      descripcion: "Comodo pantalon color gris",
      precio: 35.00,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
    {
      nombre: "Camisa Semi-Estampada",
      imagen: "/images/p10.jpg",
      marca: "american-style",
      categoria: "camisas",
      descripcion: "Comoda camisa con ligeros estampados color blanca",
      precio: 23.00,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
    {
      nombre: "Combo Hogar 2021",
      imagen: "/images/p11.jpg",
      marca: "amazon",
      categoria: "tortas",
      descripcion: "Dispositivo Alexa con accesorios",
      precio: 325.75,
      countInStock: 12,
      rating: 4.5,
      numReviews: 40,
    },
    {
      nombre: "Pods para Iphone X",
      imagen: "/images/p12.jpg",
      marca: "toshiba",
      categoria: "accesorios",
      descripcion: "Duraderos ipods para iphone color azul celeste",
      precio: 15.00,
      countInStock: 15,
      rating: 3.5,
      numReviews: 40,
    },
  ],
};

export default data;