import bcrypt from 'bcryptjs';

const data = {
  config: {
    cambioManual: 2000,
    tasaIva: 12,
    otrosImp: 2,
    montoEnvio: 9,
    mostrarBs: false,
    mostrarBcv: false,
  },
  users: [
    {
      name: 'Franklin',
      apellido: "Bolivar",
      cedula: "V7884014",
      codigo: "0001",
      email: 'frank.uah@gmail.com',
      password: bcrypt.hashSync('1331', 8),
      isAdmin: true,
      isSeller: true,
    },

  ],

  clientes: [
    {
      nombre: 'La Casa del Inyector J&D, C.A.',
      rif: "J500645988",
      direccion: "Av. Principal de los Cortijos de Lourdes Local Nro 3",
      condiciones: "Credito",
      saldo: 0.00,
    },
  ],

  productos: [
    {
      codigo: "F002",
      nombre: "LIMPIA TAPICERIA 650ML",
      imagen: "/images/F002_LIMPIA_TAPICERIA_650ML.png",
      marca: "Flamingo",
      categoria: "autos",
      descripcion: "Limpiador de Tapiceria de 650 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F003",
      nombre: "LIMPIA CAUCHO ESPUMA 650ML",
      imagen: "/images/F003_LIMPIA_CAUCHO_ESPUMA_650ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpia Caucho Espuma de 650 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F008",
      nombre: "DESENGRASANTE LIMPIA MOTOR",
      imagen: "/images/F008_DESENGRASANTE_LIMPIA_MOTOR.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Desengrasante limpia Motor",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F015",
      nombre: "INFLADOR REPARADOR DE LLANTAS 450ML",
      imagen: "/images/F015_INFLADOR_REPARADOR_DE_LLANTAS_450ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Inflador Reparador de Llantas de 450 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F016",
      nombre: "LIMPIA FRENOS 450ML",
      imagen: "/images/F016_LIMPIA_FRENOS_450ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpiador de Frenos de 450 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F024",
      nombre: "LIMPIA BRILLO TABLERO 220ML",
      imagen: "/images/F024_LIMPIA_BRILLO_TABLERO_220ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpia Vidrios y Tableros de 220 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F029",
      nombre: "LEATHER POLISH 500ML",
      imagen: "/images/F029_LEATHER_POLISH_500ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pulidor de Semi-Cuero de 500 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F030",
      nombre: "SHAMPU CAR WASH",
      imagen: "/images/F030_SHAMPU_CAR_WASH.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Shampu para vehiculos",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F037",
      nombre: "LIMPIADOR RADIADOR FLUSH 354ML",
      imagen: "/images/F037_LIMPIADOR_RADIADOR_FLUSH_354ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpiador de Radiador de 354 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F039",
      nombre: "SELLADOR RADIADOR 354ML",
      imagen: "/images/F039_SELLADOR_RADIADOR_354ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Selador e Radiador",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F041",
      nombre: "POLISH_CAR_WAX_230G.jpg",
      imagen: "/images/F041_POLISH_CAR_WAX_230G.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Cera para pulir vehiculos",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F045",
      nombre: "CLEANER FUEL INJECTOR 250ML",
      imagen: "/images/F045_CLEANER_FUEL_INJECTOR_250ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpiador de Inyectores de 250 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F047",
      nombre: "OCTANE_BOSTER_250ML.jpg",
      imagen: "/images/F047_OCTANE_BOSTER_250ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Aditivo para vehiculos de 250 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F048",
      nombre: "LIMPIA MOTOR FLUSH 443ML",
      imagen: "/images/F048_LIMPIA_MOTOR_FLUSH_443ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpiador de Motor de 443 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F049",
      nombre: "ADITIVO TRATAMIENTO MOTOR 250ML",
      imagen: "/images/F049_ADITIVO_TRATAMIENTO_MOTOR_250ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Aditivo para Motor de 250 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F055",
      nombre: "OCTANE BOOSTER 354ML",
      imagen: "/images/F055_OCTANE_BOOSTER_354ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Aditivo de 354 ML",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F056_1200",
      nombre: "PINTURA ALTA TEMPERATURA NEGRA",
      imagen: "/images/F056_1200_PINTURA_ALTA_TEMPERATURA_NEGRA.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura para altas temperaturas color negra",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F045_1300",
      nombre: "PINTURA ALTA TEMPERATURA PLATEADA",
      imagen: "/images/F056_1300_PINTURA_ALTA_TEMPERATURA_PLATEADA.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura para altas temperaturas color plateada",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F056_AMA",
      nombre: "PINTURA_AMARILLO_450ML",
      imagen: "/images/F056_PINTURA_AMARILLO_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color amarillo",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F056_MOS",
      nombre: "PINTURA AMARILLO MOSTAZA 450ML",
      imagen: "/images/F056_PINTURA_AMARILLO_MOSTAZA_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color mostaza",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
    {
      codigo: "F056_AZ_CEL",
      nombre: "F056_PINTURA_AZUL_CELESTE_450ML.png",
      imagen: "/images/F056_PINTURA_AZUL_CELESTE_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color Azul Celeste",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_AZ_CIE",
      nombre: "PINTURA AZUL CIELO 450ML",
      imagen: "/images/F056_PINTURA_AZUL_CIELO_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color Azul Cielo",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_AZ_OSC",
      nombre: "PINTURA AZUL OSCURO 450ML",
      imagen: "/images/F056_PINTURA_AZUL_OSCURO_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color Azul Cielo ",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_CHO",
      nombre: "F056_PINTURA_CHOCOLATE_450ML",
      imagen: "/images/F056_PINTURA_CHOCOLATE_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color chocolate",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_DOR",
      nombre: "F056_PINTURA_DORADO_450ML",
      imagen: "/images/F056_PINTURA_DORADO_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color dorado.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_GRI",
      nombre: "F056_PINTURA_GRIS_450ML",
      imagen: "/images/F056_PINTURA_GRIS_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color gris.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_ROJ",
      nombre: "F056_PINTURA_ROJA_450ML",
      imagen: "/images/F056_PINTURA_ROJA_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color rojo.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F056_VER",
      nombre: "PINTURA_VERDE_450ML.png",
      imagen: "/images/F056_PINTURA_VERDE_450ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura color verde.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F057",
      nombre: "SPRAY CHOMER PLATEADA 330ML",
      imagen: "/images/F057_SPRAY_CHOMER_PLATEADA_330ML.png",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Pintura spray plateada",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },

    {
      codigo: "F058",
      nombre: "LIMPIA_CONTACTO_350ML",
      imagen: "/images/F058_LIMPIA_CONTACTO_350ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Limpiador de contactos.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },


    {
      codigo: "F065",
      nombre: "LUBRICANTE_450ML",
      imagen: "/images/F065_LUBRICANTE_450ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Lubricante de 450 ML.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },


    {
      codigo: "F085",
      nombre: "BRILLO PARA CAUCHO LIQUIDO 500ML",
      imagen: "/images/F085_BRILLO_PARA_CAUCHO_LIQUIDO_500ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Brillo para cauchos de 500 ML.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },


    {
      codigo: "F089",
      nombre: "DESENGRASANTE MULTIUSO 500ML",
      imagen: "/images/F089_DESENGRASANTE_MULTIUSO_500ML.jpg",
      marca: "Flamingo",
      categoria: "autos ",
      descripcion: "Desengrasante Multiuso de 500 ML.",
      precio: 3.50,
      countInStock: 12,
      presentacion: "unidades",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};

export default data;