export const CONFIG_DOLARTODAY_REQUEST = 'CONFIG_DOLARTODAY_REQUEST';
export const CONFIG_DOLARTODAY_SUCCESS = 'CONFIG_DOLARTODAY_SUCCESS';
export const CONFIG_DOLARTODAY_FAIL = 'CONFIG_DOLARTODAY_FAIL';

export const CONFIG_DOLARBCV_REQUEST = 'CONFIG_DOLARBCV_REQUEST';
export const CONFIG_DOLARBCV_SUCCESS = 'CONFIG_DOLARBCV_SUCCESS';
export const CONFIG_DOLARBCV_FAIL = 'CONFIG_DOLARBCV_FAIL';

export const CONFIG_UPDATE_REQUEST = 'CONFIG_UPDATE_REQUEST';
export const CONFIG_UPDATE_SUCCESS = 'CONFIG_UPDATE_SUCCESS';
export const CONFIG_UPDATE_FAIL = 'CONFIG_UPDATE_FAIL';
export const CONFIG_UPDATE_RESET = 'CONFIG_UPDATE_RESET';

export const CONFIG_DETAILS_REQUEST = 'CONFIG_DETAILS_REQUEST';
export const CONFIG_DETAILS_SUCCESS = 'CONFIG_DETAILS_SUCCESS';
export const CONFIG_DETAILS_FAIL = 'CONFIG_DETAILS_FAIL';
export const CONFIG_DETAILS_RESET = 'CONFIG_DETAILS_RESET';

